"""Modern conversational English for the AAC n-gram model.

Built for someone who still thinks in full sentences: everyday talk,
questions, opinions, family, health, and body parts — not newspaper English.
Apostrophes are avoided because this keyboard only types letters.
"""

BODY_PARTS = [
    "head", "hair", "scalp", "face", "forehead", "eyebrow", "eyebrows",
    "eye", "eyes", "eyelid", "ear", "ears", "nose", "mouth", "lip", "lips",
    "tooth", "teeth", "tongue", "jaw", "chin", "cheek", "cheeks", "throat",
    "neck", "shoulder", "shoulders", "collarbone", "arm", "arms", "elbow",
    "elbows", "wrist", "wrists", "hand", "hands", "palm", "finger", "fingers",
    "thumb", "thumbs", "nail", "nails", "chest", "breast", "heart", "lung",
    "lungs", "rib", "ribs", "stomach", "belly", "abdomen", "waist", "back",
    "spine", "hip", "hips", "pelvis", "bottom", "groin", "leg", "legs",
    "thigh", "thighs", "knee", "knees", "calf", "shin", "ankle", "ankles",
    "foot", "feet", "heel", "heels", "toe", "toes", "skin", "muscle",
    "muscles", "bone", "bones", "joint", "joints", "blood",
]


def _body_sentences():
    lines = []
    for part in BODY_PARTS:
        lines.extend([
            f"my {part} hurts",
            f"my {part} is sore",
            f"my {part} itches",
            f"my {part} feels numb",
            f"my {part} is swollen",
            f"my {part} is stiff",
            f"please check my {part}",
            f"can you look at my {part}",
            f"I cannot move my {part}",
            f"I cannot feel my {part}",
            f"something is wrong with my {part}",
            f"the pain is in my {part}",
            f"it hurts in my {part}",
            f"please be careful with my {part}",
        ])
    return lines


CONVERSATION_PRIORITY = [
    "how are you",
    "how are you doing",
    "how is it going",
    "what do you think",
    "I think that",
    "I would like to",
    "I want to tell you",
    "I need to tell you",
    "can we talk",
    "can you help me",
    "thank you",
    "I love you",
    "I miss you",
    "that sounds good",
    "I am not sure",
    "let me think",
    "I do not know",
    "I understand",
    "I do not understand",
    "please tell me more",
    "what happened",
    "how was your day",
    "I am okay",
    "I am not okay",
    "my body hurts",
]

CONVERSATION_SENTENCES = [
    # Full-sentence conversation
    "how are you today",
    "how are they doing",
    "how are we doing",
    "how is everyone",
    "how is your family",
    "how was your night",
    "how was the appointment",
    "how did it go",
    "how do you feel",
    "how do you know",
    "how long will it take",
    "how much does it cost",
    "how much time do we have",
    "how many people are coming",
    "how can I help",
    "how can you tell",
    "what are you thinking",
    "what are you doing",
    "what is going on",
    "what is the plan",
    "what is happening now",
    "what time is it",
    "what day is it",
    "what do you want to do",
    "what do you need",
    "what did they say",
    "what should we do",
    "what happened yesterday",
    "where are we going",
    "where is everyone",
    "where did you go",
    "when are they coming",
    "when is my appointment",
    "when do we need to leave",
    "why is that",
    "why did that happen",
    "who is here",
    "who was that",
    "who is coming over",
    "I think so",
    "I think that is a good idea",
    "I think we should wait",
    "I think you are right",
    "I think I understand",
    "I believe you",
    "I remember that",
    "I forget what I wanted to say",
    "I meant to tell you",
    "I wanted to ask you something",
    "I have something to say",
    "I have a question",
    "I have an idea",
    "I would like some water",
    "I would like to rest",
    "I would like to go outside",
    "I would like to watch TV",
    "I would like to talk about it",
    "I would rather wait",
    "I would rather not",
    "I want to go home",
    "I want to see my family",
    "I want to hear about your day",
    "I want to finish this thought",
    "I need a minute",
    "I need more time",
    "I need you to listen",
    "I need you to repeat that",
    "I need to change position",
    "I need to use the bathroom",
    "I need my glasses",
    "I need my phone",
    "I need medicine",
    "I am trying to tell you something",
    "I am trying to remember",
    "I am looking forward to it",
    "I am tired of waiting",
    "I am glad you are here",
    "I am sorry about that",
    "I am proud of you",
    "I am worried about you",
    "I am worried about that",
    "I am happy to see you",
    "I am bored",
    "I am comfortable",
    "I am uncomfortable",
    "I am in a lot of pain",
    "I am feeling better today",
    "I am feeling worse today",
    "I can hear you",
    "I can see you",
    "I cannot hear you very well",
    "I cannot see that",
    "I cannot reach that",
    "I cannot find the words",
    "I will tell you later",
    "I will think about it",
    "I will be okay",
    "I will try",
    "I do not think so",
    "I do not like that",
    "I do not want that",
    "I do not feel well",
    "I do not remember",
    "please say that again",
    "please speak slowly",
    "please wait a second",
    "please come closer",
    "please do not leave yet",
    "please listen to me",
    "please look at me",
    "can you repeat that",
    "can you explain that",
    "can you help me sit up",
    "can you turn the TV on",
    "can you turn the TV off",
    "can you text them for me",
    "can you call them for me",
    "can you send a message",
    "can you take a picture",
    "could you please wait",
    "could you please help",
    "would you mind repeating that",
    "would you like to sit",
    "did you hear me",
    "did you get my message",
    "do you have time to talk",
    "do you know what I mean",
    "do you remember that",
    "are you serious",
    "are you okay",
    "are you coming back",
    "is that true",
    "is that okay with you",
    "is there anything else",
    "that makes sense",
    "that is a good point",
    "that is interesting",
    "that is enough for now",
    "that is not what I meant",
    "that was nice",
    "that was hard",
    "that sounds great",
    "that sounds hard",
    "this is important",
    "this is taking too long",
    "there is something I want to say",
    "there is no rush",
    "let me finish",
    "let me think about it",
    "let us talk about something else",
    "tell me about your day",
    "tell me what you think",
    "tell me if I am wrong",
    "show me later",
    "give me a second",
    "hold on a minute",
    "hang on",
    "go on",
    "keep going",
    "never mind I remember now",
    "actually I changed my mind",
    "honestly I am not sure",
    "basically I agree",
    "pretty much",
    "kind of",
    "sort of",
    "a little bit",
    "a lot",
    "too much",
    "not really",
    "not yet",
    "for sure",
    "of course",
    "no problem",
    "no worries",
    "sounds good",
    "sounds fine",
    "works for me",
    "I agree",
    "I disagree",
    "I get it",
    "I hear you",
    "fair enough",
    "maybe later",
    "maybe tomorrow",
    "see you soon",
    "see you tomorrow",
    "have a good day",
    "have a good night",
    "good luck",
    "take care",
    "I love that",
    "I hate that",
    "I like this better",
    "I prefer the other one",
    "whatever you think is best",
    "you decide",
    "your choice",
    "we can do that",
    "we should wait",
    "we should talk about it",
    "we need to be careful",
    "they are coming later",
    "they already know",
    "please call my family",
    "please text my family",
    "please tell them I love them",
    "please tell them I am okay",
    "please ask them to visit",
    "I want company",
    "I want to be alone for a minute",
    "I want quiet",
    "I want music",
    "I want the news",
    "I want a different show",
    "turn the volume up",
    "turn the volume down",
    "it is too loud",
    "it is too quiet",
    "it is too bright",
    "it is too dark",
    "it is too hot in here",
    "it is too cold in here",
    "open the window",
    "close the window",
    "I need a blanket",
    "I need a pillow",
    "the bed is uncomfortable",
    "please raise the bed",
    "please lower the bed",
    "I want to sit in the chair",
    "I want to go back to bed",
    "I want to go outside for a bit",
    "what is the weather like",
    "is it raining",
    "is it sunny",
    "I am hungry",
    "I am thirsty",
    "I am full",
    "that tastes good",
    "I do not want any more",
    "more please",
    "less please",
    "just a little",
    "I want coffee",
    "I want tea",
    "I want water",
    "I want ice chips",
    "what is for dinner",
    "what is for lunch",
    "I already ate",
    "I have not eaten yet",
    "my stomach hurts",
    "my head hurts",
    "my back hurts",
    "my chest hurts",
    "I feel sick",
    "I feel dizzy",
    "I feel weak",
    "I feel better than yesterday",
    "the medicine is helping",
    "the medicine is not helping",
    "I need a nurse",
    "I need a doctor",
    "please call a nurse",
    "it is an emergency",
    "I cannot breathe well",
    "I am having trouble breathing",
    "something does not feel right",
    "please stay with me",
    "please do not go yet",
    "come back soon",
    "I will be here",
    "I am still here",
    "nice to see you",
    "it is good to talk",
    "I enjoy talking with you",
    "you are a good listener",
    "you are kind",
    "I appreciate you",
    "thank you for coming",
    "thank you for helping me",
    "thank you for waiting",
    "sorry for the wait",
    "sorry I am slow",
    "take your time",
    "there is no hurry",
    "I am not done yet",
    "I am finished",
    "that is all I wanted to say",
    "I have more to say",
    "one more thing",
    "before I forget",
    "the point I want to make is",
    "what I mean is",
    "in other words",
    "for example",
    "the reason is",
    "because I am tired",
    "because it hurts",
    "because I miss home",
    "I used to do that",
    "I used to love that",
    "I still like that",
    "I do not do that anymore",
    "maybe someday",
    "not today",
    "today is a better day",
    "today is a hard day",
    "I slept okay",
    "I did not sleep well",
    "I had a nightmare",
    "I had a good dream",
    "can we change the subject",
    "can we go back to that",
    "I lost my train of thought",
    "where was I",
    "as I was saying",
    "anyway",
    "so what do you think",
    "does that make sense",
    "am I being clear",
    "I hope so",
    "I hope not",
    "I hope you are well",
    "please keep me updated",
    "let me know what happens",
    "text me later",
    "call me later",
    "I will wait for your answer",
    "no thank you",
    "yes please",
    "yes I would like that",
    "no I would not like that",
    "maybe we can try",
    "let us try again",
    "that did not work",
    "try a different way",
    "slow down please",
    "not so fast",
    "wait for me",
    "I am ready",
    "I am not ready",
    "give me a moment",
    "okay I am ready now",
]

COMMON_WORDS = """
a about above across actually after again against ago ahead air all almost
already also always am an and another answer any anyone anything anyway
anywhere appointment are arm around as ask at ate away back bad bag be
because become bed been before begin being believe beside best better
between big bit body book both bottom box boy bring brother brought build
bus busy but buy by call came can cannot car care careful carry case cat
catch cause chair change check child children choice choose city clean
clear close clothes coffee cold color come coming company computer
conversation cook cool copy corner cost could count country couple course
cover cross cry cup cut dad dark date daughter day dead deal dear death
decide deep describe desk did die different dinner do doctor does dog doing
done door down draw dream dress drink drive drop dry during each ear early
earth easy eat else email end enough enter even evening ever every
everyone everything exactly example except expect explain extra eye face
fact fall family far fast father feel feeling feet fell felt few field
fight figure fill film final finally find fine finger finish fire first
fish fit five floor fly follow food foot for forget form found four free
friend from front full fun funny future game garden gave get getting girl
give given glad glass go going gone good goodbye got great green ground
group grow guess gun guy had hair half hand happen happy hard has have
having he head hear heard heart heat heavy held hell hello help her here
hers herself high him himself his hold home hope hot hour house how however
huge human hundred husband I ice idea if important in inside instead into
is it its itself job join joke jump just keep kept key kill kind kitchen
knew knife know known land language large last late later laugh law lay
lead learn least leave left leg less let letter lie life light like line
list listen little live living long look looking lose lost lot love low
lunch machine made make making man many map mark matter may maybe me mean
meant meat meet meeting member mention message middle might mile milk mind
minute miss mom moment money month more morning most mother mouth move
movie much music must my myself name near nearly need needed neither never
new news next nice night no nobody none noon nor normal north nose not
note nothing now number nurse of off offer office often oh oil okay old
on once one only onto open or order other others our ours out outside over
own page pain paint pair paper parent part party pass past pay people
perhaps person phone photo pick picture piece place plan plant play please
point police poor position possible pound power pretty probably problem
put question quick quiet quite radio rain raise rather reach read ready
real really reason red remember rest result rich ride right ring rise
river road rock roll room round run sad safe said same save saw say
saying school sea season seat second see seem seen self sell send sent
serve set seven several shall she ship shirt shoe shop short should
shoulder show shut sick side sign simple since sing sister sit six size
skill skin sleep slow small smell smile snow so some someone something
sometimes son song soon sorry sort sound south space speak special spend
spoke sport spring stand star start state stay step still stop store
story street strong student study stuff such sudden sugar summer sun
sure surface system table take taken taking talk talking tall tea teach
team tell ten than thank thanks that the their them then there these they
thing things think this those though thought thousand three through throw
tie time tiny to today together told tomorrow tonight too took top total
touch toward town track trade train travel tree trip trouble true try
trying turn TV two type under understand until up upon us use used using
usual usually very video visit voice wait walk wall want wanted war warm
was wash watch water way we wear weather week weight well went were west
what whatever wheel when where whether which while white who whole whom
whose why wide wife will win wind window winter wish with within without
woman wonder word work working world worry worse worth would write wrong
yard year yes yesterday yet you young your yours yourself
""".split()


BODY_SENTENCES = _body_sentences()
