"""Seed sentences for conversation-type n-gram models.

Each entry in CORPORA is a named model you can select with
config.PREDICTION_MODEL. "aac" is modern conversational English plus
care/social needs (the default). "care" and "social" are narrower slices.

To add a conversation type: define PRIORITY + SENTENCES lists below, then
register them in CORPORA. Apostrophes are avoided because this keyboard
only types letters.
"""


from conversational_english import (
    BODY_SENTENCES,
    COMMON_WORDS,
    CONVERSATION_PRIORITY,
    CONVERSATION_SENTENCES,
)


def _dedupe(lines):
    seen = set()
    out = []
    for line in lines:
        key = line.strip().lower()
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(line)
    return out


CARE_PRIORITY = [
    "help",
    "I need help",
    "I want",
    "I need",
    "I am",
    "please help me",
    "water",
    "bathroom",
    "pain",
    "I need water",
    "I need the bathroom",
    "I am in pain",
    "I am tired",
    "I am hungry",
    "I am thirsty",
    "stop",
    "wait",
    "more please",
    "that is enough",
]

CARE_SENTENCES = [
    "I want water",
    "I want food",
    "I want coffee",
    "I want tea",
    "I want rest",
    "I want to rest",
    "I want to sleep",
    "I want to sit up",
    "I want to lie down",
    "I want to get up",
    "I want to sit in the chair",
    "I want to go back to bed",
    "I want to go outside",
    "I want to go home",
    "I want quiet",
    "I want music",
    "I want the TV",
    "I need rest",
    "I need medicine",
    "I need a nurse",
    "I need a doctor",
    "I need a blanket",
    "I need a pillow",
    "I need ice chips",
    "I need air",
    "I need help now",
    "I need to change position",
    "I need to be cleaned",
    "can you help me",
    "can you give me water",
    "can you sit me up",
    "can you turn me",
    "please give me water",
    "please turn me",
    "please sit me up",
    "please check on me",
    "I feel sick",
    "I feel better",
    "I feel worse",
    "I feel dizzy",
    "I feel weak",
    "I am hot",
    "I am cold",
    "I am uncomfortable",
    "I am done",
    "my head hurts",
    "my back hurts",
    "my neck hurts",
    "my stomach hurts",
    "my chest hurts",
    "my mouth is dry",
    "I cannot breathe well",
    "I cannot see",
    "I cannot hear you",
    "it itches",
    "please scratch my back",
    "the bed is uncomfortable",
    "raise the bed",
    "lower the bed",
    "I need to sit up",
    "I need to lie down",
    "the light is too bright",
    "it is too loud",
    "it is too hot",
    "it is too cold",
    "turn the light off",
    "turn the light on",
    "turn the volume down",
    "turn the volume up",
    "open the window",
    "close the window",
    "I want my glasses",
    "I want my phone",
    "I need the bathroom now",
    "please call a nurse",
    "please call a doctor",
    "that hurts",
    "stop that",
    "be careful",
    "slow down",
    "water please",
    "bathroom please",
    "pain medicine please",
    "I want help",
    "help me please",
    "help me",
    "good",
    "bad",
    "better",
    "worse",
    "right now",
]

SOCIAL_PRIORITY = [
    "yes",
    "no",
    "please",
    "thank you",
    "hello",
    "I love you",
    "how are you",
    "okay",
]

SOCIAL_SENTENCES = [
    "hi",
    "good morning",
    "good afternoon",
    "good night",
    "goodbye",
    "see you later",
    "I am fine",
    "I am okay",
    "I am not okay",
    "I miss you",
    "you are kind",
    "I appreciate you",
    "please stay",
    "do not leave",
    "please come here",
    "please come closer",
    "nice to see you",
    "thank you so much",
    "thanks",
    "sorry",
    "excuse me",
    "sure",
    "maybe",
    "I do not know",
    "I do not understand",
    "please say that again",
    "please speak slowly",
    "please listen",
    "I want to talk",
    "I have something to say",
    "yes please",
    "no thank you",
    "not yet",
    "maybe later",
    "I changed my mind",
    "never mind",
    "wait a minute",
    "give me a minute",
    "please wait",
    "please stop",
    "can you come here",
    "can you wait",
    "can you stop",
    "go ahead",
    "not now",
    "later",
    "again",
    "more",
    "less",
    "enough",
    "I want company",
    "I am scared",
    "I am lonely",
    "I am happy",
    "I am sad",
    "I am angry",
    "I am bored",
    "call my family",
    "please call my mom",
    "please call my dad",
    "please call my wife",
    "please call my husband",
    "please call my daughter",
    "please call my son",
    "please call my sister",
    "please call my brother",
    "what time is it",
    "what day is it",
    "what is happening",
    "who is here",
    "where is everyone",
    "when is my appointment",
    "how long",
    "tell me a story",
    "read to me",
    "stay with me",
    "I like that",
    "I do not like that",
    "that is good",
    "that is bad",
    "that is better",
    "try again",
    "I am finished",
    "I am ready",
    "one more time",
    "please look at me",
    "I am here",
    "I need you",
    "come back",
    "in a little while",
]

# Full conversational AAC set: care + social + modern full-sentence English.
PRIORITY_SENTENCES = _dedupe(CARE_PRIORITY + SOCIAL_PRIORITY + CONVERSATION_PRIORITY)
SENTENCES = _dedupe(CARE_SENTENCES + SOCIAL_SENTENCES + BODY_SENTENCES + CONVERSATION_SENTENCES)

# Named conversation-type models. "brown" lives in predictor.py (NLTK corpus).
CORPORA = {
    "aac": {
        "priority": PRIORITY_SENTENCES,
        "sentences": SENTENCES,
        "vocab": COMMON_WORDS,
    },
    "care": {
        "priority": CARE_PRIORITY,
        "sentences": _dedupe(CARE_SENTENCES + BODY_SENTENCES),
        "vocab": COMMON_WORDS,
    },
    "social": {
        "priority": _dedupe(SOCIAL_PRIORITY + CONVERSATION_PRIORITY),
        "sentences": _dedupe(SOCIAL_SENTENCES + CONVERSATION_SENTENCES),
        "vocab": COMMON_WORDS,
    },
}
